const gantry = @import("gantry");
pub const layers: []const gantry.rules.Layer = &.{
    .{ .name = "types", .patterns = &.{"src/types.zig"} },
    .{ .name = "wire", .patterns = &.{ "src/wire.zig", "src/wire/**" } },
    .{ .name = "certificate", .patterns = &.{ "src/certificate.zig", "src/certificate/**" } },
    .{ .name = "authentication owners", .patterns = &.{ "src/verify.zig", "src/verify/**", "src/Verification.zig", "src/credentials.zig", "src/credentials/**", "src/PrivateKey.zig", "src/Identity.zig", "src/ClientAuth.zig", "src/Trust.zig", "src/services.zig", "src/services/**" } },
    .{ .name = "native verification driver", .patterns = &.{"src/NativeVerification.zig"} },
    .{ .name = "certificates module", .patterns = &.{"src/certificates.zig"} },
    .{ .name = "TLS wire and crypto", .patterns = &.{ "src/tls/wire.zig", "src/tls/wire/**", "src/tls/crypto.zig", "src/tls/crypto/**" } },
    .{ .name = "TLS record", .patterns = &.{ "src/tls/record.zig", "src/tls/record/**" } },
    .{ .name = "TLS handshake", .patterns = &.{ "src/tls/handshake.zig", "src/tls/handshake/**" } },
    .{ .name = "TLS connection", .patterns = &.{ "src/tls/Connection.zig", "src/tls/connection/**", "src/tls/quic.zig", "src/tls/quic/**" } },
    .{ .name = "TLS stream", .patterns = &.{ "src/tls/Session.zig", "src/tls/session/**" } },
    .{ .name = "TLS module", .patterns = &.{"src/tls.zig"} },
    .{ .name = "portable probes", .patterns = &.{ "src/portable.zig", "src/portable/**" } },
    .{ .name = "cloak", .patterns = &.{"src/root.zig"} },
};
pub const required = [_][]const u8{"src/root.zig"};
pub const entries: []const []const u8 = &.{"src/root.zig"};
pub const modules: []const gantry.NamedModule = &.{.{ .name = "probes", .path = "src/portable.zig" }};
// Runtime sibling owners cannot import one another; test edges remain free.
const sibling_references = [_]gantry.rules.ReferenceRule{
    .{ .name = "independent authentication owners", .from = "src/verify.zig", .target = "src/credentials.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/verify.zig", .target = "src/credentials/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/verify.zig", .target = "src/PrivateKey.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/verify.zig", .target = "src/Identity.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/verify.zig", .target = "src/ClientAuth.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/verify.zig", .target = "src/Trust.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/verify/**", .target = "src/credentials.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/verify/**", .target = "src/credentials/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/verify/**", .target = "src/PrivateKey.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/verify/**", .target = "src/Identity.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/verify/**", .target = "src/ClientAuth.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/verify/**", .target = "src/Trust.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/Verification.zig", .target = "src/credentials.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/Verification.zig", .target = "src/credentials/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/Verification.zig", .target = "src/PrivateKey.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/Verification.zig", .target = "src/Identity.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/Verification.zig", .target = "src/ClientAuth.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/Verification.zig", .target = "src/Trust.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/verify.zig", .target = "src/services.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/verify.zig", .target = "src/services/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/verify/**", .target = "src/services.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/verify/**", .target = "src/services/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/Verification.zig", .target = "src/services.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/Verification.zig", .target = "src/services/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/credentials.zig", .target = "src/verify.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/credentials.zig", .target = "src/verify/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/credentials.zig", .target = "src/Verification.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/credentials/**", .target = "src/verify.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/credentials/**", .target = "src/verify/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/credentials/**", .target = "src/Verification.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/PrivateKey.zig", .target = "src/verify.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/PrivateKey.zig", .target = "src/verify/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/PrivateKey.zig", .target = "src/Verification.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/Identity.zig", .target = "src/verify.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/Identity.zig", .target = "src/verify/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/Identity.zig", .target = "src/Verification.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/ClientAuth.zig", .target = "src/verify.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/ClientAuth.zig", .target = "src/verify/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/ClientAuth.zig", .target = "src/Verification.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/Trust.zig", .target = "src/verify.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/Trust.zig", .target = "src/verify/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/Trust.zig", .target = "src/Verification.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/credentials.zig", .target = "src/services.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/credentials.zig", .target = "src/services/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/credentials/**", .target = "src/services.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/credentials/**", .target = "src/services/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/PrivateKey.zig", .target = "src/services.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/PrivateKey.zig", .target = "src/services/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/Identity.zig", .target = "src/services.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/Identity.zig", .target = "src/services/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/ClientAuth.zig", .target = "src/services.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/ClientAuth.zig", .target = "src/services/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/Trust.zig", .target = "src/services.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/Trust.zig", .target = "src/services/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/services.zig", .target = "src/verify.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/services.zig", .target = "src/verify/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/services.zig", .target = "src/Verification.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/services/**", .target = "src/verify.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/services/**", .target = "src/verify/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/services/**", .target = "src/Verification.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/services.zig", .target = "src/credentials.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/services.zig", .target = "src/credentials/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/services.zig", .target = "src/PrivateKey.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/services.zig", .target = "src/Identity.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/services.zig", .target = "src/ClientAuth.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/services.zig", .target = "src/Trust.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/services/**", .target = "src/credentials.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/services/**", .target = "src/credentials/**", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/services/**", .target = "src/PrivateKey.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/services/**", .target = "src/Identity.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/services/**", .target = "src/ClientAuth.zig", .relative = true, .kind = .import },
    .{ .name = "independent authentication owners", .from = "src/services/**", .target = "src/Trust.zig", .relative = true, .kind = .import },
};
const package_references = [_]gantry.rules.ReferenceRule{.{ .name = "named dependencies", .unresolved_only = true, .except_targets = &.{ "std", "builtin", "shakedown", "aegis" } }};
pub const references: []const gantry.rules.ReferenceRule = &(package_references ++ sibling_references);
pub const owned: []const gantry.rules.TokenRule = &(durability ++ no_async);

/// Durable writes go through airlock.
const durability = [_]gantry.rules.TokenRule{.{
    .name = "durability belongs to airlock",
    .sequences = &.{
        &.{ ".", "sync", "(" },
        &.{ ".", "syncFile", "(" },
        &.{ ".", "syncDir", "(" },
        &.{ "createFileAtomic", "(" },
        &.{ "fsync", "(" },
        &.{ "fdatasync", "(" },
        &.{ "FlushFileBuffers", "(" },
    },
}};

/// The caller owns asynchronous work.
const no_async = [_]gantry.rules.TokenRule{.{
    .name = "async belongs to the caller",
    .sequences = &.{&.{ "io", ".", "async", "(" }},
}};
