//! Writes `src/crypto/p256/table.zig`, the P-256 base comb, from the standard library's P-256:
//! `zig run ci/p256_table.zig > src/crypto/p256/table.zig`. Entry j of window i is the affine
//! point (j + 1) * 2^(bits * i) * G as Montgomery limbs (R = 2^256), x then y. A cloak test
//! recomputes every entry and compares.
const std = @import("std");
const P256 = std.crypto.ecc.P256;

pub const bits = 6;
pub const windows = 43;
pub const entries = 1 << (bits - 1);

pub fn compute(out: *[windows][entries][8]u64) !void {
    var base = P256.basePoint;
    for (0..windows) |i| {
        var point = base;
        for (0..entries) |j| {
            const affine = point.affineCoordinates();
            out[i][j] = affine.x.limbs ++ affine.y.limbs;
            point = point.add(base);
        }
        for (0..bits) |_| base = base.dbl();
    }
}

pub fn main(init: std.process.Init) !void {
    var buffer: [1 << 16]u8 = undefined;
    var stdout = std.Io.File.stdout().writerStreaming(init.io, &buffer);
    const w = &stdout.interface;
    const out = try init.gpa.create([windows][entries][8]u64);
    defer init.gpa.destroy(out);
    try compute(out);
    try w.print(
        \\//! The P-256 base comb, generated by `zig run ci/p256_table.zig`; do not edit. Entry j of
        \\//! window i is (j + 1) * 2^({d} * i) * G in affine Montgomery limbs (R = 2^256), x then y.
        \\pub const bits = {d};
        \\pub const windows = {d};
        \\pub const base: [windows][1 << (bits - 1)][8]u64 = .{{
        \\
    , .{ bits, bits, windows });
    for (out) |window| {
        try w.writeAll("    .{\n");
        for (window) |entry| {
            try w.writeAll("        .{ ");
            for (entry, 0..) |limb, k| try w.print("0x{x:0>16}{s}", .{ limb, if (k == 7) "" else ", " });
            try w.writeAll(" },\n");
        }
        try w.writeAll("    },\n");
    }
    try w.writeAll("};\n");
    try w.flush();
}
